Csv component adding
AurisP/GoodFilmsApp pull request #22
Opened 2024-05-03 12:10 UTC by AurisP

Added full CSV component functionality. Rebased ontop of data_access_fix

2024-05-04 10:32 UTC, mihkelaaremae requested changes
Rebase to master, I can't get a good overview with commits from another branch in the diff.

2024-05-05 18:20 UTC, mihkelaaremae approved these changes

2024-05-05 18:20 UTC, mihkelaaremae commented on GoodFilmsApp/PosterHandler.cs
> +            ref Ref<string> path) : base(controller)
No need to use ref Ref<string>, use Ref<string> instead.

2024-05-05 18:20 UTC, mihkelaaremae commented on GoodFilmsApp/CSView.cs
> +            var count = exporter.saveDataToCsv(ref filmArray, checkBoxAppend.Checked);
Canceling a Windows Save dialog causes a crash here

2024-05-05 18:20 UTC, mihkelaaremae commented on GoodFilmsApp/CSView.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
It might be a good idea to put some info here about what the "Save As" menu should even do. I've got no clue what "delimiter" or "text qualifier" or "pick new file" are. If this component exports as CSV then the button should say "export as CSV" for example.

2024-05-05 19:03 UTC, merged

2024-05-05 19:06 UTC, kreban commented
Merged but needs some additional fixes: add column names on CSV files and remove escape characters from movie info text.